config/routes.rb
Rails.application.routes.draw do
  get 'role_managers/index'
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :role_managers, only:[:index, :edit]
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Article, status: "public"  

    if user.present?# additional permissions for logged in users (they can read their own posts)    
      can :manage, Article, user_id: user.id
      can :read, :all

      if user.has_role? :admin # additional permissions for administrators
        can :manage, :all
      end
    end
    # if user.has_role? :admin
    #   can :manage, :all
    # else
    #   can :read, :all
    # end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    acts_as_paranoid
    resourcify
    belongs_to :user
    has_many:comments,dependent: :destroy

    validates:title, presence:true
    validates:body, presence:true,length:{minimum:10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  
  validates:commenter, presence:true
  validates:body, presence:true,length:{minimum:5}
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES=['public','private','archived']

    included do
        validates:status,inclusion:{in: VALID_STATUSES}
    end

    class_methods do
        def public_count
            where(status:'public').count
        end
    end

    def archived?
        status=='archived'
    end
    
    def public?
        status=='public'
    end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action:authenticate_user! , except: [:index,:show] 
    load_and_authorize_resource 

  def index
    @status= params[:status]? params[:status] : 'public'
    @articles=Article.all.where(:status => @status).paginate(page: params[:page], per_page:2).order('created_at DESC')
end

def show
    @article=Article.find(params[:id])
end

def new
    @article=Article.new
end

def create 
    @article=current_user.articles.new(article_params)
    if @article.save
        redirect_to root_path  
    else
        render :new
    end
end

def edit
    @article=Article.find(params[:id])
end
def update
    @article=Article.find(params[:id])
    if @article.update(article_params)
        redirect_to @article
    else
        render :edit
    end
end

def destroy
    @article=Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
end

private
    def article_params
        params.require(:article).permit(:title,:body,:status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action:authenticate_user! 
    def create
        @article=Article.find(params[:article_id]) 
        @comment= @article.comments.new(comment_params)
        @comment.commenter=current_user.email
        if @comment.save
            redirect_to article_path(@article)
        end
    end

    def destroy
        @article=Article.find(params[:article_id])
        @comment=@article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:body,:status)
        end
end

app/controllers/role_managers_controller.rb
class RoleManagersController < ApplicationController
  def index
    @user=User.all
  end

  def edit
    @user=User.find(params[:id])
    if @user.has_role? :admin 
        @user.remove_role :admin
    else
      @user.add_role :admin
    end
    redirect_to role_managers_index_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/role_managers_helper.rb
module RoleManagersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.select :status,['public','private','archived'],selected:'public' %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
\<%= render "form",article:@article %>

app/views/articles/index.html.erb
 <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Welcome To
          <small>Drunk Blogger</small>
        </h1>
        <%= form_tag(root_path, :method => "get") do %>
          <%= select_tag(:status, options_for_select(['public','private','archived'],@status)) %>
          <%= submit_tag("Search") %>
        <% end %>
        Our blog has <%=Article.public_count%> articles and counting!

        <!-- Blog Post -->
        <%@articles.each do |article|%>
        <div class="card mb-4">
          <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
          <div class="card-body">
            <h2 class="card-title"><%=article.title%></h2>
            <p class="card-text"><%=truncate(article.body, length:200)%></p>
            <%= link_to "Read More..", article, class: "btn btn-primary" %>
          </div>
          <div class="card-footer text-muted">
          <%=article.created_at.strftime('%B %e at %l:%M %p')%> by
            <a href="#"><%=User.find(article.user_id).email%></a>
          </div>
        </div>
    <%end%>

        
        <!-- Pagination -->
        <%= will_paginate @articles %>
      </div>

      <!-- Sidebar Widgets Column -->
      <%=render "shared/aside"%>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>



    

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article:@article %>

app/views/articles/show.html.erb
<!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-md-8">

        <!-- Title -->
        <h1 class="mt-4"><%= @article.title%></h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#"><%=User.find(@article.user_id).email %></a>
        </p>

        <% if can? :update, @article %><%= link_to "Edit article", edit_article_path(@article) %> | <%end%>
            <% if can? :update, @article %><%= link_to "Delete", article_path(@article),method: :delete,data:{confirm:"Are you sure?"} %><%end%>

        <hr>

        <!-- Date/Time -->
        <p><%=@article.created_at.strftime('%B %e at %l:%M %p')%></p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead text-justify"><%= @article.body %></p>
        <hr>

        <!-- Comments Form -->
        <%= render "comments/form" %>
        
        <!-- Single Comment -->
        <%= render "comments/comment" %>
      
      </div>

      <!-- Sidebar Widgets Column -->

        <%=render "shared/aside"%> 


    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

<footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

app/views/comments/_comment.html.erb
<%@article.comments.each do |comment|%>
<%if  comment.public?%>
    <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0"><%=comment.commenter%></h5>
            <%=comment.body%>
            <%= link_to "DeleteComment", [comment.article,comment],method: :delete,data:{confirm:"Are You Sure?"} %>
            </div>
      </div>
<%end%>
<%end%>

app/views/comments/_form.html.erb
<%=form_with model:[@article,@article.comments.build] do |form|%>
<div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <%=form.text_area :body,class: "form-control", size: "90x5"  %>
              </div>
              <%= form.label :status, "Status" %><br>
              <%= form.select :status,['public','private','archived'], class: "custom-select mr-sm-2" ,selected:'public' %>
              <br><br>
              <%=form.submit%>
            </form>
          </div>
</div>
<%end%>

app/views/layouts/_navbar.html.erb
 <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Drunk Blogger", root_path ,class:"navbar-brand"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path ,class:"nav-link active"%>
          </li>
          <li class="nav-item">
            <%= link_to "New_Article", new_article_path ,class: "nav-link" %>
          </li>
          <li class="nav-item">
          <% if current_user && current_user.has_role?(:admin) %>
                <%= link_to "Manage Users", role_managers_index_path,   class:"nav-link" %>
          <%end%>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path ,method: :delete ,class:"nav-link"%>
                <%else%>
                <%= link_to "Sign In", new_user_session_path,   class:"nav-link" %>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrunkBlogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
    <%= yield %>
    
  </body>
</html>

app/views/role_managers/index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">User_Id</th>
      <th scope="col">Email</th>
      <th scope="col">Admin</th>
      <th scope="col">Admin_Role</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user|%>
    <tr>
      <th scope="row"><%=user.id%></th>
      <td><%=user.email%></td>
      <td><%=user.has_role?(:admin)%></td>
      <td>
      <%if user.has_role?(:admin)%>
        <%= link_to "Remove Admin", edit_role_manager_path(user)%>
        <%else%>
        <%= link_to "Make Admin ", edit_role_manager_path(user)%>
        <%end%>  
    </td>

    </tr>
    <%end%>
    
  </tbody>
</table>

app/views/shared/_aside.html.erb
<div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
        
        <!--user-card widget-->
          <%=render "shared/user-card" %>
        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

</div>

app/views/shared/_user-card.html.erb
<% if user_signed_in? %>
    <div class="card p-3">
        <div class="d-flex align-items-center">
            <div class="image"> <img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="rounded" width="155"> </div>
            <div class="ml-3 w-100">
                <h4 class="mb-0 mt-0">Alex Morrision</h4> <span><%=current_user.email%></span>
                <small><p>Author id :<%=current_user.id%></p></small>
                <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                    <div class="d-flex flex-column"> <span class="articles">Articles</span> <span class="number1">38</span> </div>
                    <div class="d-flex flex-column"> <span class="followers">Followers</span> <span class="number2">980</span> </div>
                    <div class="d-flex flex-column"> <span class="rating">Rating</span> <span class="number3">8.9</span> </div>
                </div>
                <div class="button mt-2 d-flex flex-row align-items-center"> <button class="btn btn-sm btn-outline-primary w-100">Chat</button> <button class="btn btn-sm btn-primary w-100 ml-2">Follow</button> </div>
            </div>
        </div>
    </div>
<%end%>